### ISSUE TITLE
weired issue

### ISSUE THREAD

**Issue by wanghaisheng** [nitotm/efficient-language-detector-py#1]
from eld import LanguageDetector

text="4444"
detector = LanguageDetector()

lang=detector.detect(text).language
print(lang)

text=4444
detector = LanguageDetector()

lang=detector.detect(text).language
print(lang)

**Comment by nitotm** [comment]
Well detect() expects a string, as explained in the documentation, any digit alone should not return any language anyways.

The integer is obviously failing: 'int' object is not subscriptable

All can I do is add:
```python
if not isinstance(text, str):
    raise TypeError("Input 'text' must be a string.")
```
But I also think, does sending an integer to a language detector have to be handled? Also, all this fix will do is give another fatal error, is it necessary another error cause when the current error is `'int' object is not subscriptable`

What do you think?

**Comment by nitotm** [comment]
I added the fix, since there weren't any cons to it. If there is nothing more I will close the issue.

**Comment by wanghaisheng** [comment]
thanks though, earlier I catch the input type to avoid this
